# Creating Numpy Arrays

In [5]:
import numpy as np

# One-dimensional array
x=[1,2,3,4,5]
arr = np.array(x)
arr


array([1, 2, 3, 4, 5])

In [6]:
# Two-dimensional array
y=[[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(y)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# 2D array of zeros
arr= np.zeros((5,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
# 2D array of ones
arr = np.ones((5,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
# 2D arra of random numbers
arr=np.random.random([3,2])
arr

array([[0.13190319, 0.44145494],
       [0.34140227, 0.03228852],
       [0.88486352, 0.36961832]])

In [14]:
# Array within a given interval
arr=np.arange(1,30,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [15]:
# Array of a given length
arr = np.linspace(0,20,5)
arr

array([ 0.,  5., 10., 15., 20.])

# Basic Array Operations

In [20]:
a=np.array([100,200,300])
b=np.array([[20,25,30],[40,50,60]])

In [22]:
# Numpy Addition
np.add(a,b)

# or
a+b

array([[120, 225, 330],
       [140, 250, 360]])

In [24]:
# Numpy Subtraction
np.subtract(a,b)

# or
a-b

array([[ 80, 175, 270],
       [ 60, 150, 240]])

In [25]:
# Numpy Multiplication

np.multiply(a,b)

# or
a*b

array([[ 2000,  5000,  9000],
       [ 4000, 10000, 18000]])

In [26]:
# Numpy Division

np.divide(a,b)

# or
a/b

array([[ 5. ,  8. , 10. ],
       [ 2.5,  4. ,  5. ]])

# Numpy Aggregate Functions

- `np.sum()` - Returns the sum of array elements over a given axis.
- `np.prod()` - Return the product of array elements over a given axis.
- `np.mean()` - Computes the arithmetic mean along the specified axis.
- `np.std()` - Computes the standard deviation along the specified axis.
- `np.var()` - Computes the variance along the specified axis.
- `np.min()` - Returns the indices of the minimum valyues along an axis.
- `np.max()` - Returns the indices of the maximum values along an axis.
- `np.all()` - Checks if all array elements along a given axis evaluate to True.
- `np.any()` - Checks if any array element along a given axis evaluates to True.
- `np.cumsum()` - Returns the cumulative sum of the elemennts along a given axis.
- `np.cumprod()` - Returns the cumulative product of the elements along a given axis.

# NumPy Array Manipulation

In [27]:
np.arange(1,40,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])

### Reshaping Arrays

In [28]:
# Reshaping 1D array
np.arange(1,40,4).reshape(5,2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29],
       [33, 37]])

### Transposing Arrays

In [29]:
# Transposing 2D array
arr = np.arange(1,40,4).reshape(5,2)
arr.transpose()

# or
arr.T

array([[ 1,  9, 17, 25, 33],
       [ 5, 13, 21, 29, 37]])

### Concatenating Arrays

In [31]:
arr1 = np.array([[1,2,3,4],[2,3,7,11]])
arr2 = np.array([[1,3,5,7],[2,4,6,8]])

# Concatenating both arrays
np.concatenate((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 2,  3,  7, 11],
       [ 1,  3,  5,  7],
       [ 2,  4,  6,  8]])

In [32]:
# Concatenating both arrays on columns
np.concatenate((arr1, arr2), axis=1)

array([[ 1,  2,  3,  4,  1,  3,  5,  7],
       [ 2,  3,  7, 11,  2,  4,  6,  8]])

### Joining Arrays

In [33]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,3,5,7])

# Joining the arrays
np.stack((arr1,arr2), axis=1)

array([[1, 1],
       [2, 3],
       [3, 5],
       [4, 7]])

In [34]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,3,5,7])
arr3=np.array([2,4,6,8])

# Joining the arrays
np.column_stack((arr1, arr2, arr3))

array([[1, 1, 2],
       [2, 3, 4],
       [3, 5, 6],
       [4, 7, 8]])

In [36]:
# Joining the arr2 to ar1
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 1, 3, 5, 7])

In [35]:
# Joining the arr2 to arr1
np.vstack((arr1, arr2))

array([[1, 2, 3, 4],
       [1, 3, 5, 7]])

### Splitting Arrays

In [38]:
a = np.arange(20)

# Splitting the array into 4 pieces
np.split(a,4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

### Flattening an Array

In [39]:
arr = np.array([[20,25,30,35],
                [40,50,60,70],
                [45,48,51,54]])

np.ravel(arr)

array([20, 25, 30, 35, 40, 50, 60, 70, 45, 48, 51, 54])

In [40]:
np.ravel(arr, order='F')

array([20, 40, 45, 25, 50, 48, 30, 60, 51, 35, 70, 54])

In [41]:
arr.flatten()

array([20, 25, 30, 35, 40, 50, 60, 70, 45, 48, 51, 54])